config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :users
  resources :shops
  resources :sessions
  resources :assistants
  resources :products
  resources :properties
  resources :brands
  resources :orders
  resources :order_items
  post 'get_brand' => 'products#getBrand'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= Admin.new # guest user (not logged in)
      if user.role=='Admin'
        can :manage, :all
        cannot :edit, :shop
        cannot :create, :product
      elsif user.role=='ShopOwner'
        can :manage, AssistantsController
        can :manage, Shop, :id => user.shop_id 
        can :manage, Product, :shop_id => user.shop_id 
        can :manage, Property do |property|
          user.shop.products.include?(property.product)
        end
        can :manage, OrderItem do |orderitem|
          user.shop.products.include?(orderitem.property.product)
        end
        cannot :delete, OrderItem
      else 
        can :update, :product
      end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
	belongs_to :shop
	mount_uploader :avatar, AvatarUploader
	enum gender: %w[Male Female]
	enum role: %w[Admin ShopOwner Assistant]
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	has_secure_password
	belongs_to :user

	def sign_in
    update(access_token: add_token)
  end

  def sign_in_with_account_social(token)
    update(access_token: add_token(token))
  end

  def add_token(token = generate_access_token)
    _new_tokens = self.access_token
    _new_tokens.shift() if _new_tokens.length >= 2
    _new_tokens.push(token)
    _new_tokens
  end

  def generate_access_token
    SecureRandom.urlsafe_base64
  end

  def generate_confirm_token
    update_attributes(confirm_token: generate_access_token, confirm_send_at: Time.now)
  end

  def confirm_token_valid?
    (self.confirm_send_at + 10.minutes) > Time.now
  end

  def confirmed_email
    self.confirm_token = nil
    self.confirm_at = Time.now
  end

  def access_token
    JSON.parse(self[:access_token])["tokens"]
  end

  def access_token=(value)
    self[:access_token] = { tokens: value }.to_json
  end

  def remove_token(token)
    new_tokens = self.access_token
    new_tokens.delete(token).present? ? update(access_token: new_tokens) : false
  end

  # Sign in with facebook

  def self.find_or_create_account_social(provider, uid)
    Authentication.find_or_initialize_by(provider: provider, uid: uid)
  end

  def self.create_user_with_account_social(authSocial, avatar)
    User.create(
      avatar: avatar,
      name: authSocial['name']
    )
  end

  def self.sign_in_with_account_social(access_token, provider, uid, authSocial, avatar)
    _auth = find_or_create_account_social(provider, uid)
    if _auth.id.present?
      _auth.sign_in_with_account_social(access_token)
    else
      ActiveRecord::Base.transaction do
        user = create_user_with_account_social(authSocial, avatar)
        _auth.update(
          access_token: [access_token],
          user_id: user.id,
          provider: provider,
          uid: uid,
          password: 'no password'
        )
      end
    end
    _auth
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	has_many :categories, through: :category_brands
end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set

  has_many :brands, through: :category_brands
  has_many :properties
  has_many :products

  def self.menu_categories
    categories = Hash.new
    Category.roots.each do |cat|
      cat_menu = Hash.new
      cat.children.each do |childCat|

        cat_leaf_at = Hash.new
        child = childCat.children.to_a
        childC = child.to_a
        childCat.children.each_with_index do |cCat, index|
          if cCat.descendants != []
            cat_leaf = Hash.new
            cat_leaf[cCat.title] = cCat.children
            childC.delete_at(index)
            childC[index] = cat_leaf
          else
            childC[index] = cCat
          end
        end
        cat_menu[childCat.title] = childC
      end
      categories[cat.title] = cat_menu
    end
    categories
  end
	
end

app/models/category_brand.rb
class CategoryBrand < ApplicationRecord
	belongs_to :category
  belongs_to :brand
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :property
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
  belongs_to :property
  has_one :product, through: :property
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :properties, :dependent => :destroy 
	belongs_to :brand
	has_many :comments
  has_many :order_items
	belongs_to :shop
	accepts_nested_attributes_for :properties, :allow_destroy => true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :product
	has_many :images, :dependent => :destroy 
	has_many :order_items

end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :admins, :dependent => :destroy 
	accepts_nested_attributes_for :admins, :allow_destroy => true
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
	has_many :authentications
	has_many :orders
	has_many :comments
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
	def brand_arrays
		brand_arr = Array.new
		@brands=Brand.select(:branch).distinct
		@brands.each do |brand|
			brand_arr.push(brand.branch)
		end
		return brand_arr
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<%= cloudinary_js_config %> 
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Edit Information</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Form validation <small>sub title</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= form_for current_user do |f| %>
          	<div class="form-horizontal form-label-left">
            <p>For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a>
            </p>
            <span class="section">Personal Info</span>

            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
              	<%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Phone <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :phone, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Change Password <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :password, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
           	<div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Image <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
               <%= f.file_field :avatar  %>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Cancel</button>
                <%= f.submit 'Submit', class: 'btn btn-success'%>
              </div>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<script type="text/javascript">
  $('.cloudinary-fileupload').cloudinary_fileupload();
</script>
   
	
  

app/views/admins/index.html.erb
  <!-- /top navigation -->
    <!-- page content -->
      <div class="">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Shop Owner List <small>Shop Management</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <div class="table-responsive">
                  <table class="table table-striped jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title">Id </th>
                        <th class="column-title">Attend Date </th>
                        <th class="column-title">Name </th>
                        <th class="column-title">Email </th>
                        <th class="column-title">Shop </th>
                        <th class="column-title">Amount </th>
                        <th class="column-title no-link last"><span class="nobr">Action</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @admins.each do |admin| %>
                      <tr class="even pointer">
                        <td class="a-center ">
                          <input type="checkbox" class="flat" name="table_records">
                        </td>
                        <td class=" "><%=admin.id%></td>
                        <td class=" "><%= admin.created_at %></td>
                        <td class=" "><%= admin.name %></td>
                        <td class=" "><%= admin.email %></td>
                        <% if admin.shop %>
                          <td class=" "><%= admin.shop.name %></td>
                        <% else %>
                          <td class=" ">NOT AN OWNER</td>
                        <% end %>
                        <td class="a-right a-right ">$7.45</td>
                        <td class=" last">
                          <a href="#"> View </a>
                          <%= link_to "Delete", admin_path(admin), method: 'Delete'%>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- /page content -->

    <!-- footer content -->
    
    <!-- /footer content -->
  </div>
</div>

app/views/admins/show.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Information of <%= current_user.name%></h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Form validation <small>sub title</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          	<div class="form-horizontal form-label-left">
            <p>For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a>
            </p>
            <span class="section">Personal Info</span>

            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="form-control col-md-7 col-xs-12"> <%= current_user.name%> </label> 
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Phone <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="form-control col-md-7 col-xs-12"> <%= current_user.phone%> </label>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Gender <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="form-control col-md-7 col-xs-12"> <%= current_user.gender %> </label>
              </div>
            </div>
            <div class="item form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Role <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <label class="form-control col-md-7 col-xs-12"> <%= current_user.role %> of <%= current_user.shop.name%> </label>
              </div>
            </div>
            <div class="ln_solid"></div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
   
	
  

app/views/layouts/_asidebar.html.erb
      <div class="left_col scroll-view" style="height: 100%">
        <div class="navbar nav_title" style="border: 0;">
          <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Fanatic!</span></a>
        </div>
        <div class="clearfix"></div>
        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
          <%= cl_image_tag(current_user.avatar, :width => 50, :height => 50, class: 'img-circle profile_img') %>
          </div>
          <div class="profile_info">
            <span>Welcome,</span>
            <h2><%= current_user.name%></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->
        <br />
        
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
              <li>
                <%=link_to 'Home', root_path %>
              </li>
              <% if can? :manage, :all %>
              <li><a><i class="fa fa-edit"></i> User <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><%= link_to 'Edit Profile', edit_admin_path(current_user) %></li>
                  <li><%= link_to 'Make Shop Owner', new_shop_path %></li>
                  <li><%= link_to 'User List', users_path %></li>
                  <li><%= link_to 'Shop Owner List', admins_path %></li>
                </ul>
              </li>
              <% end %>
              <li><a><i class="fa fa-edit"></i> Shop <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><%= link_to 'My shop', shop_path(current_user.shop) %></li>
                  <li><%= link_to 'Set Assistant', new_assistant_path %></li>
                  <li><%= link_to 'Product Management', products_path %></li>
                </ul>
              </li>
              <li><a><i class="fa fa-table"></i> Order <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="tables.html">Process</a></li>
                  <li><%= link_to 'Completed Order', order_items_path %></li>
                </ul>
              </li>
              <li><a><pathass="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="chartjs.html">Shop Revenue</a></li>
                  <li><a href="morisjs.html">Product Revenue</a></li>
                  <li><a href="morisjs.html">People Reach</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="menu_section">
            <h3>Live On</h3>
            <ul class="nav side-menu">
              <li>
                <a><i class="fa fa-bug"></i> Setting Up Home Page </a>
              </li>
              <li>
                <a><i class="fa fa-sitemap"></i> Fanatic Website </a>
              </li>
            </ul> 
          </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <%= link_to logout_path, method: :delete do %>
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          <% end %>
        </div>
        <!-- /menu footer buttons -->
      </div>

app/views/layouts/_footer.html.erb
<footer>
      <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
      </div>
      <div class="clearfix"></div>
 </footer>

app/views/layouts/_navbar.html.erb
<div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <img src="https://beebom-redkapmedia.netdna-ssl.com/wp-content/uploads/2016/01/Reverse-Image-Search-Engines-Apps-And-Its-Uses-2016.jpg" alt="">John Doe
                <span class=" fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li><a href="javascript:;"> Profile</a></li>
                <li>
                  <a href="javascript:;">
                    <span class="badge bg-red pull-right">50%</span>
                    <span>Settings</span>
                  </a>
                </li>
                <li><a href="javascript:;">Help</a></li>
                <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
              </ul>
            </li>

            <li role="presentation" class="dropdown">
              <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-envelope-o"></i>
                <span class="badge bg-green">6</span>
              </a>
              <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                <li>
                  <a>
                    <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                    <span>
                      <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                    </span>
                    <span class="message">
                      Film festivals used to be do-or-die moments for movie makers. They were where...
                    </span>
                  </a>
                </li>
                <li>
                  <a>
                    <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                    <span>
                      <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                    </span>
                    <span class="message">
                      Film festivals used to be do-or-die moments for movie makers. They were where...
                    </span>
                  </a>
                </li>
                <li>
                  <a>
                    <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                    <span>
                      <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                    </span>
                    <span class="message">
                      Film festivals used to be do-or-die moments for movie makers. They were where...
                    </span>
                  </a>
                </li>
                <li>
                  <a>
                    <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                    <span>
                      <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                    </span>
                    <span class="message">
                      Film festivals used to be do-or-die moments for movie makers. They were where...
                    </span>
                  </a>
                </li>
                <li>
                  <div class="text-center">
                    <a>
                      <strong>See All Alerts</strong>
                      <i class="fa fa-angle-right"></i>
                    </a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminFanaticWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="nav-md" style="background-color: #F7F7F7 !important;">
    <div class="container body">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
  	  <div class="main_container" >
      <% if logged_in? == true %>
    	  <div class="col-md-3 left_col" >
          <%= render 'layouts/asidebar' %> 
        </div>
        <div class="right-col" >
          <%= render 'layouts/navbar' %> 
          <div class="right_col" role="main">
            <%= yield %>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
      </div>
    </div>
  <%= javascript_include_tag 'application' %>
  
  </body>
</html>