config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :users
  resources :shops
  resources :sessions
  resources :assistants
  resources :products
  resources :properties
  resources :brands
  resources :orders
  resources :order_items
  post 'get_brand' => 'products#getBrand'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= Admin.new # guest user (not logged in)
      if user.role=='Admin'
        can :manage, :all
        cannot :edit, :shop
        cannot :create, :product
      elsif user.role=='ShopOwner'
        can :manage, AssistantsController
        can :manage, Shop, :id => user.shop_id 
        can :manage, Product, :shop_id => user.shop_id 
        can :manage, Property do |property|
          user.shop.products.include?(property.product)
        end
        can :manage, OrderItem do |orderitem|
          user.shop.products.include?(orderitem.property.product)
        end
        cannot :delete, OrderItem
      else 
        can :update, :product
      end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
	belongs_to :shop
	mount_uploader :avatar, AvatarUploader
	enum gender: %w[Male Female]
	enum role: %w[Admin ShopOwner Assistant]
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	has_secure_password
	belongs_to :user

	def sign_in
    update(access_token: add_token)
  end

  def sign_in_with_account_social(token)
    update(access_token: add_token(token))
  end

  def add_token(token = generate_access_token)
    _new_tokens = self.access_token
    _new_tokens.shift() if _new_tokens.length >= 2
    _new_tokens.push(token)
    _new_tokens
  end

  def generate_access_token
    SecureRandom.urlsafe_base64
  end

  def generate_confirm_token
    update_attributes(confirm_token: generate_access_token, confirm_send_at: Time.now)
  end

  def confirm_token_valid?
    (self.confirm_send_at + 10.minutes) > Time.now
  end

  def confirmed_email
    self.confirm_token = nil
    self.confirm_at = Time.now
  end

  def access_token
    JSON.parse(self[:access_token])["tokens"]
  end

  def access_token=(value)
    self[:access_token] = { tokens: value }.to_json
  end

  def remove_token(token)
    new_tokens = self.access_token
    new_tokens.delete(token).present? ? update(access_token: new_tokens) : false
  end

  # Sign in with facebook

  def self.find_or_create_account_social(provider, uid)
    Authentication.find_or_initialize_by(provider: provider, uid: uid)
  end

  def self.create_user_with_account_social(authSocial, avatar)
    User.create(
      avatar: avatar,
      name: authSocial['name']
    )
  end

  def self.sign_in_with_account_social(access_token, provider, uid, authSocial, avatar)
    _auth = find_or_create_account_social(provider, uid)
    if _auth.id.present?
      _auth.sign_in_with_account_social(access_token)
    else
      ActiveRecord::Base.transaction do
        user = create_user_with_account_social(authSocial, avatar)
        _auth.update(
          access_token: [access_token],
          user_id: user.id,
          provider: provider,
          uid: uid,
          password: 'no password'
        )
      end
    end
    _auth
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	has_many :categories, through: :category_brands
end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set

  has_many :brands, through: :category_brands
  has_many :properties
  has_many :products

  def self.menu_categories
    categories = Hash.new
    Category.roots.each do |cat|
      cat_menu = Hash.new
      cat.children.each do |childCat|

        cat_leaf_at = Hash.new
        child = childCat.children.to_a
        childC = child.to_a
        childCat.children.each_with_index do |cCat, index|
          if cCat.descendants != []
            cat_leaf = Hash.new
            cat_leaf[cCat.title] = cCat.children
            childC.delete_at(index)
            childC[index] = cat_leaf
          else
            childC[index] = cCat
          end
        end
        cat_menu[childCat.title] = childC
      end
      categories[cat.title] = cat_menu
    end
    categories
  end
	
end

app/models/category_brand.rb
class CategoryBrand < ApplicationRecord
	belongs_to :category
  belongs_to :brand
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :property
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
  belongs_to :property
  has_one :product, through: :property
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :properties, :dependent => :destroy 
	belongs_to :brand
	has_many :comments
  has_many :order_items
	belongs_to :shop
	accepts_nested_attributes_for :properties, :allow_destroy => true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :product
	has_many :images, :dependent => :destroy 
	has_many :order_items

end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :admins, :dependent => :destroy 
	accepts_nested_attributes_for :admins, :allow_destroy => true
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
	has_many :authentications
	has_many :orders
	has_many :comments
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

	def new
    @shop = Shop.new
    @admin = @shop.admins.build
  end

  def create
    password = set_auto_password
    params[:shop][:admins_attributes]["0"][:password] = password
    params[:shop][:admins_attributes]["0"][:role] = 1
    @shop = Shop.new(shop_params)
      if @shop.save 
        AdminMailer.registration_email(@shop.admins.first,password).deliver_now
        redirect_to @shop, notice: 'shop was successfully created.' 
      else
        render :new 
      end
    end

  def show
  	 @shop = Shop.find(params[:id])
  	 @admin = @shop.admins.find_by(role: 1)
  	 @assistant = @shop.admins.where(role: 2)
  end

  def index
  	@shops=Shop.all
  end

  private

  def shop_params
  	params.require(:shop).permit(:name,:address, admins_attributes: [:name, :user_name, :password, :gender, :email, :role, :phone]) 
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
	def brand_arrays
		brand_arr = Array.new
		@brands=Brand.select(:branch).distinct
		@brands.each do |brand|
			brand_arr.push(brand.branch)
		end
		return brand_arr
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end

  def current_user
    return unless session[:user_id]
    if(Admin.find(session[:user_id])!=nil)
   	  @current_user ||= Admin.find(session[:user_id])
   	else
   		log_out
   	  redirect_to login_path
   	end
  end
 def logged_in?
    !current_user.nil?
  end

   # Confirms a logged-in user.
  # def user_signed_in?
  #   unless logged_in?
  #     flash[:danger] = "Please log in."
  #     redirect_to login_path
  #   end
  # end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shops/_user_field.html.erb
<div class="col-md-6 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Shop Owner Form <small>as a shop owner</small></h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
  <!-- start form for validation -->
        <div id="demo-form" data-parsley-validate>
          <label for="fullname">Full Name * :</label>
          <%=f.text_field :name, class: 'form-control' %>
          <label for="email">Email * :</label>
          <%=f.text_field :email, class: 'form-control' %>
          <label for="email">Username * :</label>
          <%=f.text_field :user_name, class: 'form-control' %>
           <label for="email">Phone * :</label>
          <%=f.text_field :phone, class: 'form-control' %>
          <label>Gender *:</label>
          <p>
            Male:
            <%= f.radio_button :gender, 'Male', :checked => true, class: 'flat' %> 
            Female:
            <%= f.radio_button :gender, 'Female', :checked => true, class: 'flat' %>
          </p>
          <label>Role *:</label>
          <p>
            Shop owner:
            <%= f.radio_button :role, 'ShopOwner', :checked => true, class: 'flat' %> 
            Shop assistant:
            <%= f.radio_button :role, 'Assistant', class: 'flat' %> 
          </p>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
  <!-- /top navigation -->
    <!-- page content -->
      <div class="">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Shop List <small>Shop Management</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <div class="table-responsive">
                  <table class="table table-striped jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title">Id </th>
                        <th class="column-title">Name </th>
                        <th class="column-title">Address </th>
                        <th class="column-title">Owner </th>
                        <th class="column-title">Contact </th>
                        <th class="column-title no-link last"><span class="nobr">Action</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @shops.each do |shop| %>
                      <tr class="even pointer">
                        <td class="a-center ">
                          <input type="checkbox" class="flat" name="table_records">
                        </td>
                        <td class=" "><%= shop.id%></td>
                        <td class=" "><%= shop.name %></td>
                        <td class=" "><%= shop.address %></td>
                        <% if shop.admins.first %>
                        <td class=" "><%= shop.admins.first.name %></td>
                        <td class=" "><%= shop.admins.first.phone %></td>
                        <% else %>
                        <td class=" ">Still no owner</td>
                        <td class=" ">No phone</td>
                        <% end %>
                        <td class=" last">
                           <%= link_to 'View', shop_path(shop), method: 'GET' %>
                          <%= link_to 'Delete', shop_path(shop), method: 'Delete' %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- /page content -->

    <!-- footer content -->
    
    <!-- /footer content -->
  </div>
</div>

app/views/shops/new.html.erb
<%=form_for @shop, url: shops_path, method: 'POST' do |f| %>
  <div class="col-md-6 col-xs-12">
  	<div class="x_panel">
  		<div class="x_title">
  			<h2>Shop Registration <small>your shop information</small></h2>
  			<div class="clearfix"></div>
  		</div>
  		<div class="x_content">
  	<!-- start form for validation -->
  				<div id="demo-form" data-parsley-validate>
  		  		<label for="fullname">Name Shop* :</label>
  		  		<%=f.text_field :name, class: 'form-control' %>
  		  		<label for="email">Address* :</label>
  		  		<%=f.text_field :address, class: 'form-control' %>
            <label for="email">Which type* :</label>
            <select class="form-control">
              <option>Company</option>
              <option>Personal</option>
            </select>
  				</div>
  		</div>
  	</div>
    <div class="x_panel">
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    </div>
  </div>
  <%= f.fields_for :admins do |builder| %>
    <%= render 'shops/user_field', :f => builder %>
  <% end %>
  <%= f.submit 'Submit Form', class: 'btn btn-primary text-center form-control' %>
<% end %>	

         

app/views/shops/show.html.erb
<div class="col-md-6 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>Shop Information <small>your shop information</small></h2>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
	<!-- start form for validation -->
				<div id="demo-form" data-parsley-validate>
					<div class="form-group">
		  		<label for="fullname">Name Shop* :</label>
		  		<span for="fullname"><%=@shop.name%></span>
		  		</div>
		  		<div class="form-group">
		  		<label for="fullname">Address* :</label>
		  		<span for="fullname"><%=@shop.address%></span>
		  		</div>
		  		<div class="form-group">
		  		<label for="email">Type* :</label>
		  		<span for="fullname">Personal</span>
		  		</div>
				</div>
		</div>
	</div>
	<div class="x_panel">
		<div class="x_title">
			<h2>Shop Owner <small>personal info</small></h2>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
	<!-- start form for validation -->
				<div id="demo-form" data-parsley-validate>
					<div class="form-group">
		  		<label for="fullname">Name Owner* :</label>
		  		<span for="fullname"><%=@admin.name%></span>
		  		</div>
		  		<div class="form-group">
		  		<label for="fullname">Email* :</label>
		  		<span for="fullname"><%=@admin.email%></span>
		  		</div>
		  		<div class="form-group">
		  		<label for="fullname">Phone* :</label>
		  		<span for="fullname">12345678</span>
		  		</div>
		  		<div class="form-group">
		  		<label for="fullname">Role :</label>
		  		<span for="fullname"><%=@admin.role%></span>
		  		</div>
				</div>
		</div>
	</div>
</div>
<div class="col-md-6 col-sm-6 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Assistant of This Shop</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">

      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Role</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        	<% @assistant.each do |assist| %>
	          <tr>
	            <td scope="row"><%=assist.id%></td>
	            <td><%=assist.name%></td>
	            <td><%=assist.role%></td>
	            <td><%=assist.phone%></td>
	            <td><%=assist.email%></td>
	            <td><%= link_to 'Delete', admin_path(assist), method: 'Delete' %></td>
	          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="x_panel">
    <div class="x_title">
      <h2><i class="fa fa-bars"></i> Tabs </h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="" role="tabpanel" data-example-id="togglable-tabs">
        <ul id="myTab1" class="nav nav-tabs bar_tabs right" role="tablist">
          <li role="presentation" class="active"><a href="#tab_content11" id="home-tabb" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Information</a>
          </li>
          <li role="presentation" class=""><a href="#tab_content22" role="tab" id="profile-tabb" data-toggle="tab" aria-controls="profile" aria-expanded="false">Revenue</a>
          </li>
        </ul>
        <div id="myTabContent2" class="tab-content">
          <div role="tabpanel" class="tab-pane fade active in" id="tab_content11" aria-labelledby="home-tab">
          	<% if @shop.logo %>
              <%= image_tag @shop.logo, class: 'class="img-circle profile_img',style: 'width: 20%;' %>
            <% end %>
            <p>
            	<div class="form-group">
		  					<label for="email">Slogan :</label>
		  					<span for="fullname"><%= @shop.slogan %></span>
		  				</div>
		  				<div class="form-group">
		  					<label for="email">Description :</label>
		  					<span for="fullname"><%= @shop.description %></span>
		  				</div>
            </p>
          </div>
          <div role="tabpanel" class="tab-pane fade" id="tab_content22" aria-labelledby="profile-tab">
          	<div class="col-md-6 col-sm-6 col-xs-12">
	            <div class="form-group">
			  				<label for="email">Total:</label>
			  				<span for="fullname">$ 123</span>
			  			</div>
			  			<div class="form-group">
			  				<label for="email">This month:</label>
			  				<span for="fullname">$ 123</span>
			  			</div>
			  			<div class="form-group">
			  				<label for="email">Revenue Increase:</label>
			  				<span for="fullname">$ 123</span>
			  			</div>
			  		</div>
			  		<div class="col-md-6 col-sm-6 col-xs-12">
	            <div class="form-group">
			  				<label for="email">Orders quantity (this month):</label>
			  				<span for="fullname">123</span>
			  			</div>
			  			<div class="form-group">
			  				<label for="email">Rating:</label>
			  				<span for="fullname">$ 123</span>
			  			</div>
			  			<a href="#">More details</a>
			  		</div>
	        </div>
        </div>
      </div>
    </div>
  </div>
</div>




       