config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :users
  resources :shops
  resources :sessions
  resources :assistants
  resources :products
  resources :properties
  resources :brands
  resources :orders
  resources :order_items
  post 'get_brand' => 'products#getBrand'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= Admin.new # guest user (not logged in)
      if user.role=='Admin'
        can :manage, :all
        cannot :edit, :shop
        cannot :create, :product
      elsif user.role=='ShopOwner'
        can :manage, AssistantsController
        can :manage, Shop, :id => user.shop_id 
        can :manage, Product, :shop_id => user.shop_id 
        can :manage, Property do |property|
          user.shop.products.include?(property.product)
        end
        can :manage, OrderItem do |orderitem|
          user.shop.products.include?(orderitem.property.product)
        end
        cannot :delete, OrderItem
      else 
        can :update, :product
      end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
	belongs_to :shop
	mount_uploader :avatar, AvatarUploader
	enum gender: %w[Male Female]
	enum role: %w[Admin ShopOwner Assistant]
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	has_secure_password
	belongs_to :user

	def sign_in
    update(access_token: add_token)
  end

  def sign_in_with_account_social(token)
    update(access_token: add_token(token))
  end

  def add_token(token = generate_access_token)
    _new_tokens = self.access_token
    _new_tokens.shift() if _new_tokens.length >= 2
    _new_tokens.push(token)
    _new_tokens
  end

  def generate_access_token
    SecureRandom.urlsafe_base64
  end

  def generate_confirm_token
    update_attributes(confirm_token: generate_access_token, confirm_send_at: Time.now)
  end

  def confirm_token_valid?
    (self.confirm_send_at + 10.minutes) > Time.now
  end

  def confirmed_email
    self.confirm_token = nil
    self.confirm_at = Time.now
  end

  def access_token
    JSON.parse(self[:access_token])["tokens"]
  end

  def access_token=(value)
    self[:access_token] = { tokens: value }.to_json
  end

  def remove_token(token)
    new_tokens = self.access_token
    new_tokens.delete(token).present? ? update(access_token: new_tokens) : false
  end

  # Sign in with facebook

  def self.find_or_create_account_social(provider, uid)
    Authentication.find_or_initialize_by(provider: provider, uid: uid)
  end

  def self.create_user_with_account_social(authSocial, avatar)
    User.create(
      avatar: avatar,
      name: authSocial['name']
    )
  end

  def self.sign_in_with_account_social(access_token, provider, uid, authSocial, avatar)
    _auth = find_or_create_account_social(provider, uid)
    if _auth.id.present?
      _auth.sign_in_with_account_social(access_token)
    else
      ActiveRecord::Base.transaction do
        user = create_user_with_account_social(authSocial, avatar)
        _auth.update(
          access_token: [access_token],
          user_id: user.id,
          provider: provider,
          uid: uid,
          password: 'no password'
        )
      end
    end
    _auth
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	has_many :categories, through: :category_brands
end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set

  has_many :brands, through: :category_brands
  has_many :properties
  has_many :products

  def self.menu_categories
    categories = Hash.new
    Category.roots.each do |cat|
      cat_menu = Hash.new
      cat.children.each do |childCat|

        cat_leaf_at = Hash.new
        child = childCat.children.to_a
        childC = child.to_a
        childCat.children.each_with_index do |cCat, index|
          if cCat.descendants != []
            cat_leaf = Hash.new
            cat_leaf[cCat.title] = cCat.children
            childC.delete_at(index)
            childC[index] = cat_leaf
          else
            childC[index] = cCat
          end
        end
        cat_menu[childCat.title] = childC
      end
      categories[cat.title] = cat_menu
    end
    categories
  end
	
end

app/models/category_brand.rb
class CategoryBrand < ApplicationRecord
	belongs_to :category
  belongs_to :brand
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :property
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
  belongs_to :property
  has_one :product, through: :property
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :properties, :dependent => :destroy 
	belongs_to :brand
	has_many :comments
  has_many :order_items
	belongs_to :shop
	accepts_nested_attributes_for :properties, :allow_destroy => true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :product
	has_many :images, :dependent => :destroy 
	has_many :order_items

end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :admins, :dependent => :destroy 
	accepts_nested_attributes_for :admins, :allow_destroy => true
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
	has_many :authentications
	has_many :orders
	has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        redirect_to @user, notice: 'User was successfully created.' 
        render :show, status: :created, location: @user 
      else
        render :new 
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit 
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
	def brand_arrays
		brand_arr = Array.new
		@brands=Brand.select(:branch).distinct
		@brands.each do |brand|
			brand_arr.push(brand.branch)
		end
		return brand_arr
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end

  def current_user
    return unless session[:user_id]
    if(Admin.find(session[:user_id])!=nil)
   	  @current_user ||= Admin.find(session[:user_id])
   	else
   		log_out
   	  redirect_to login_path
   	end
  end
 def logged_in?
    !current_user.nil?
  end

   # Confirms a logged-in user.
  # def user_signed_in?
  #   unless logged_in?
  #     flash[:danger] = "Please log in."
  #     redirect_to login_path
  #   end
  # end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
  <!-- /top navigation -->
    <!-- page content -->
      <div class="">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>User List <small>User Management</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <div class="table-responsive">
                  <table class="table table-striped jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title">Id </th>
                        <th class="column-title">Name </th>
                        <th class="column-title">Uid </th>
                        <th class="column-title">Provider </th>
                        <th class="column-title">Address </th>
                        <th class="column-title">Phone </th>
                        <th class="column-title no-link last"><span class="nobr">Action</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @users.each do |user| %>
                      <tr class="even pointer">
                        <td class="a-center ">
                          <input type="checkbox" class="flat" name="table_records">
                        </td>
                        <td class=" "><%= user.id%></td>
                        <td class=" "><%= user.name %></td>
                        <td class=" " >
                          <% if user.authentications.length !=0 %>
                            <% user.authentications.each do |auth| %>
                              <%= auth.uid %> <br>
                            <% end %>
                        <% end %>
                         </td>
                         <td class=" " >
                          <% if user.authentications.length !=0 %>
                            <% user.authentications.each do |auth| %>
                              <%= auth.provider %> <br>
                            <% end %>
                        <% end %>
                         </td>
                        <td class=" "><%= user.address %></td>
                        <td class="a-right a-right "> <%=user.phone%></td>
                        <td class=" last">
                          <a href="#"> View </a>
                          <%= link_to 'Delete', user_path(user), method: 'Delete' %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- /page content -->

    <!-- footer content -->
    
    <!-- /footer content -->
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>