config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :users
  resources :shops
  resources :sessions
  resources :assistants
  resources :products
  resources :properties
  resources :brands
  resources :orders
  resources :order_items
  post 'get_brand' => 'products#getBrand'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= Admin.new # guest user (not logged in)
      if user.role=='Admin'
        can :manage, :all
        cannot :edit, :shop
        cannot :create, :product
      elsif user.role=='ShopOwner'
        can :manage, AssistantsController
        can :manage, Shop, :id => user.shop_id 
        can :manage, Product, :shop_id => user.shop_id 
        can :manage, Property do |property|
          user.shop.products.include?(property.product)
        end
        can :manage, OrderItem do |orderitem|
          user.shop.products.include?(orderitem.property.product)
        end
        cannot :delete, OrderItem
      else 
        can :update, :product
      end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
	belongs_to :shop
	mount_uploader :avatar, AvatarUploader
	enum gender: %w[Male Female]
	enum role: %w[Admin ShopOwner Assistant]
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	has_secure_password
	belongs_to :user

	def sign_in
    update(access_token: add_token)
  end

  def sign_in_with_account_social(token)
    update(access_token: add_token(token))
  end

  def add_token(token = generate_access_token)
    _new_tokens = self.access_token
    _new_tokens.shift() if _new_tokens.length >= 2
    _new_tokens.push(token)
    _new_tokens
  end

  def generate_access_token
    SecureRandom.urlsafe_base64
  end

  def generate_confirm_token
    update_attributes(confirm_token: generate_access_token, confirm_send_at: Time.now)
  end

  def confirm_token_valid?
    (self.confirm_send_at + 10.minutes) > Time.now
  end

  def confirmed_email
    self.confirm_token = nil
    self.confirm_at = Time.now
  end

  def access_token
    JSON.parse(self[:access_token])["tokens"]
  end

  def access_token=(value)
    self[:access_token] = { tokens: value }.to_json
  end

  def remove_token(token)
    new_tokens = self.access_token
    new_tokens.delete(token).present? ? update(access_token: new_tokens) : false
  end

  # Sign in with facebook

  def self.find_or_create_account_social(provider, uid)
    Authentication.find_or_initialize_by(provider: provider, uid: uid)
  end

  def self.create_user_with_account_social(authSocial, avatar)
    User.create(
      avatar: avatar,
      name: authSocial['name']
    )
  end

  def self.sign_in_with_account_social(access_token, provider, uid, authSocial, avatar)
    _auth = find_or_create_account_social(provider, uid)
    if _auth.id.present?
      _auth.sign_in_with_account_social(access_token)
    else
      ActiveRecord::Base.transaction do
        user = create_user_with_account_social(authSocial, avatar)
        _auth.update(
          access_token: [access_token],
          user_id: user.id,
          provider: provider,
          uid: uid,
          password: 'no password'
        )
      end
    end
    _auth
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	has_many :categories, through: :category_brands
end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set

  has_many :brands, through: :category_brands
  has_many :properties
  has_many :products

  def self.menu_categories
    categories = Hash.new
    Category.roots.each do |cat|
      cat_menu = Hash.new
      cat.children.each do |childCat|

        cat_leaf_at = Hash.new
        child = childCat.children.to_a
        childC = child.to_a
        childCat.children.each_with_index do |cCat, index|
          if cCat.descendants != []
            cat_leaf = Hash.new
            cat_leaf[cCat.title] = cCat.children
            childC.delete_at(index)
            childC[index] = cat_leaf
          else
            childC[index] = cCat
          end
        end
        cat_menu[childCat.title] = childC
      end
      categories[cat.title] = cat_menu
    end
    categories
  end
	
end

app/models/category_brand.rb
class CategoryBrand < ApplicationRecord
	belongs_to :category
  belongs_to :brand
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
  belongs_to :product
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :property
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
  belongs_to :property
  has_one :product, through: :property
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	has_many :properties, :dependent => :destroy 
	belongs_to :brand
	has_many :comments
  has_many :order_items
	belongs_to :shop
	accepts_nested_attributes_for :properties, :allow_destroy => true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :product
	has_many :images, :dependent => :destroy 
	has_many :order_items

end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :admins, :dependent => :destroy 
	accepts_nested_attributes_for :admins, :allow_destroy => true
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
	has_many :authentications
	has_many :orders
	has_many :comments
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:edit, :show, :destroy]
	def index
		@products = Product.where(shop_id: current_user.shop_id)
		@product = Product.new
		@property = @product.properties.build
	end

	def create 
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    @product.brand_id = params[:brand_id]
    binding.pry
      if @product.save 
        redirect_to edit_product_path(@product), notice: 'Product was successfully created with their property.' 
      else
        render :index
        flash[:danger]="Something went wrong. Try to do again!"
      end
	end

	def destroy
		@product.destroy
		redirect_to products_path, notice: 'Delete product completed'
	end

	def edit 
		@property = Property.new
	end

	def update
		@product.category_id = params[:category_id]
		if @product.update(product_params)
			redirect_to edit_product_path, notice: 'Update Product information successfully!'
		else 
			render :edit
			flash[:danger]= 'Cannot update'
		end
	end

	def getBrand
		@arr = Array.new
		@arr = brand_arrays_follow_category(params[:valueCat])
		respond_to do |format|
      format.js { render :layout => false }
      format.json { render json: @arr }
    end
	end

	private

	def set_product
		@product=Product.find(params[:id])
	end

	def product_params
    params.require(:product).permit(:name, :description, :category_id, :shop_id, properties_attributes: [:size, :price, :storage, :color])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
	def brand_arrays
		brand_arr = Array.new
		@brands=Brand.select(:branch).distinct
		@brands.each do |brand|
			brand_arr.push(brand.branch)
		end
		return brand_arr
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end

  def current_user
    return unless session[:user_id]
    if(Admin.find(session[:user_id])!=nil)
   	  @current_user ||= Admin.find(session[:user_id])
   	else
   		log_out
   	  redirect_to login_path
   	end
  end
 def logged_in?
    !current_user.nil?
  end

   # Confirms a logged-in user.
  # def user_signed_in?
  #   unless logged_in?
  #     flash[:danger] = "Please log in."
  #     redirect_to login_path
  #   end
  # end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_property_field.html.erb
<div class="form-horizontal form-label-left col-md-12 col-sm-12 col-xs-12">
  <div class="form-group">
    <label class="col-md-5 col-sm-3 col-xs-12 control-label">
      <h3>Add Property</h3>
    </label>
    <div class="col-md-7 col-sm-9 col-xs-12">
    </div>
  </div>
  <div class="form-horizontal form-label-left">
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Size (Ex: M,XL,L)</label>
    <div class="col-md-5 col-sm-9 col-xs-12">
      <%= f.text_field :size, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Storage (GB) </label>
    <div class="col-md-5 col-sm-9 col-xs-12">
    <%= f.text_field :storage, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Color</label>
    <div class="col-md-5 col-sm-9 col-xs-12">
         <%= select_tag :color, options_for_select(color_arrays), class: "select2_group form-control" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Price ($)</label>
    <div class="col-md-5 col-sm-9 col-xs-12">
      <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>
   <div class="form-group">
    <div class="col-md-5 col-sm-9 col-xs-12 col-md-offset-3">
  </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Product Page</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
   <% if @product.properties[0] %>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>You are watching the information of product id <%=@product.id %></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="col-md-7 col-sm-7 col-xs-12">
           
            	<% if @product.properties[0].images.length>0 %>
                <div class="product-image">
                  <%= image_tag(@product.properties[0].images[0].image) %>
                </div>
              <% end %>
              <div class="product_gallery">
                <% if @product.properties[0].images.length>1 %>
              	  <% @product.properties[0].images.each do |image| %>
                  <a>
                    <%= image_tag(image.image) %>
                  </a>
                  <% end %>
                <% end %>
              </div>
            
          </div>
          <div class="col-md-5 col-sm-5 col-xs-12" style="border:0px solid #e5e5e5;">
            <h3 class="prod_title"><%=@product.name%></h3>
            <p>A product of <b><%=@product.category.title%></b></p>
            <p>Description: <%=@product.description%></p>
            <br />

            <div class="">
              <h2>Available Colors</h2>
              <ul class="list-inline prod_color">
              	<%@product.properties.each do |property|%>
              	  <% if property.color=="Black"%>
                    <li>
                      <p><%= property.color %></p>
                      <div class="color" style="background-color: black"></div>
                    </li>
                	<% end %>
                	<% if property.color=="Blue"%>
                    <li>
                      <p><%= property.color %></p>
                      <div class="color bg-blue"></div>
                    </li>
                	<% end %>
                	<% if property.color=="Red"%>
                    <li>
                      <p><%= property.color %></p>
                      <div class="color bg-red"></div>
                    </li>
                	<% end %>
                	<% if property.color=="Orange"%>
                    <li>
                      <p><%= property.color %></p>
                      <div class="color bg-orange"></div>
                    </li>
                	<% end %>
                <% end %>
              </ul>
            </div>
            <br />
            <div class="">
          		<% if @product.properties[0].size!=nil %>
            		<h2>Size</h2>
                <ul class="list-inline prod_size">
                	<%@product.properties.each do |property|%>
                    <li>
                      <button type="button" class="btn btn-default btn-xs"><%=property.size%></button>
                    </li>
                  <% end %>
                </ul>
                 <%end%>
            </div>
            <div class="">
          		<% if @product.properties[0].storage!=nil %>
            		<h2>Storage</h2>
                <ul class="list-inline prod_size">
                	<%@product.properties.each do |property|%>
                    <li>
                      <button type="button" class="btn btn-default btn-xs"><%=property.storage%></button>
                    </li>
                  <% end %>
                </ul>
                 <%end%>
            </div>
            <div class="">
          		<% if @product.properties[0].size!=nil %>
            		<h2>Size</h2>
                <ul class="list-inline prod_size">
                	<%@product.properties.each do |property|%>
                    <li>
                      <button type="button" class="btn btn-default btn-xs"><%=property.size%></button>
                    </li>
                  <% end %>
                </ul>
                 <%end%>
            </div>
            <div class="">
              <table  class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Color</th>
                  <th>Size</th>
                  <th>Storage</th>
                  <th>Price</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                 <%@product.properties.each do |property|%>
                  <tr>
                    <td><%=property.color%></td>
                    <td><%=property.size%></td>
                    <td><%=property.storage%> GB</td>
                    <td>$ <%=property.price%></td>
                    <td><%= link_to 'Delete', property_path(property), method: 'DELETE' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <p>This product dont have any properties. Please fill the new one! </p> 
  <% end %>
</div>
  <div >
   <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Edit This product</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for @product, url: product_path(@product),:remote => true, method: :patch do |f| %>
        <div class="form-horizontal form-label-left">
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
            	<%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Description </label>
            <div class="col-md-9 col-sm-9 col-xs-12">
            <%= f.text_field :description, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Category</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
          	 <%= select_tag :category_id,  grouped_options_for_select(category_arrays, @product.category.id), class: 'select2_group form-control ' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Brand</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <%= select_tag :brand_id, options_for_select(brand_arrays), class: 'select2_group form-control '%>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Input Tags</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" />
              <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
            </div>
          </div>
           <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
            <%= f.submit 'SAVE', class: "btn btn-primary"%>
          </div>
          </div>
        </div>
        <% end %>
   </div>
   </div>

    <div class="x_panel">
      <div class="x_title">
        <h2>Property</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
       <%= form_for @property, url: properties_path(@property) do |f| %>
        <div class="form-horizontal form-label-left col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <label class="col-md-5 col-sm-3 col-xs-12 control-label">
            	<h3>Add Property</h3>
            </label>
            <div class="col-md-7 col-sm-9 col-xs-12">
            </div>
          </div>
          <div class="form-horizontal form-label-left">
            	<%= f.hidden_field :product_id, :value => @product.id%>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Size (Ex: M,XL,L)</label>
            <div class="col-md-5 col-sm-9 col-xs-12">
            	<%= f.text_field :size, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Storage (GB) </label>
            <div class="col-md-5 col-sm-9 col-xs-12">
            <%= f.text_field :storage, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Color</label>
            <div class="col-md-5 col-sm-9 col-xs-12">
              	 <%= select_tag :color, options_for_select(color_arrays), class: "select2_group form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Price ($)</label>
            <div class="col-md-5 col-sm-9 col-xs-12">
              <%= f.text_field :price, class: 'form-control' %>
            </div>
          </div>
           <div class="form-group">
            <div class="col-md-5 col-sm-9 col-xs-12 col-md-offset-3">
          <%= f.submit 'CREATE', class: "btn btn-primary"%>
          </div>
          </div>
        </div>
       <% end %>
   </div>
   </div>
   <div class="clearfix"></div>
      <div class="x_content">
    </div>
  </div> 
</div>
<script type="text/javascript">
  $('#category_id').change(function() {
      var value =  $('#category_id').val();
       $.ajax({
          url:'../../get_brand',
          type:'POST',
          dataType:'json',
          data:{
              valueCat: value,
          },
          dataType: 'script',
          success:function(data){
            console.log(data);
          },
          error:function(data){
              console.log(data);
          }
      });
    });
</script>

app/views/products/getBrand.js.erb
$('#brand_id').replaceWith('<%= escape_javascript(select_tag :brand_id, options_for_select(@arr), class: 'select2_group form-control') %>');

app/views/products/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Product Management</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="">
    <div class="x_panel">
      <div class="x_title">
        <h2><i class="fa fa-bars"></i> Tabs <small>Float left</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="" role="tabpanel" data-example-id="togglable-tabs">
          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
            <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Product List</a>
            </li>
            <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Add Product</a>
            </li>
            <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Most concern</a>
            </li>
          </ul>
          <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="x_panel">
                    <div class="x_content">
                      <p class="text-muted font-13 m-b-30">
                        DataTables has most features enabled by default, so all you need to do to use it with your own tables is to call the construction function: <code>$().DataTable();</code>
                      </p>
                      <table id="datatable" class="table table-striped table-bordered">
                        <thead>
                          <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Rating</th>
                            <th>Category</th>
                            <th>Number Review</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%@products.each do |product|%>
                            <tr>
                              <td><%=product.id%></td>
                              <td><%=product.name%></td>
                              <td><%=product.description%></td>
                              <td><%=product.rating%></td>
                              <td><%=product.category.title%></td>
                              <td><%=product.number_review%></td>
                              <td><%= link_to 'Edit', edit_product_path(product)%>
                              <%= link_to 'Delete', product_path(product), method: 'DELETE'%></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
              <div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Product Page</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div >
   <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Edit This product</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for @product, url: products_path, :remote => true, method: :post do |f| %>
          <%= f.hidden_field :shop_id, :value => current_user.shop_id %>
        <div class="form-horizontal form-label-left">
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Description </label>
            <div class="col-md-9 col-sm-9 col-xs-12">
            <%= f.text_field :description, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Category</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
             <%= select_tag :category_id,  grouped_options_for_select(category_arrays), class: 'select2_group form-control' %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Brand</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
                 <%= select_tag :brand_id, options_for_select([[1,1],[2,2]])%>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">Input Tags</label>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" />
              <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
            </div>
          </div>
           <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
            
          </div>
          </div>
        </div>
      <div class="x_title">
        <h2>Property</h2>
        
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= f.fields_for :properties do |builder| %>
           <%= render 'products/property_field', :f => builder %>
        <% end %>
         <div class="control-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
            <div class="col-md-9 col-sm-9 col-xs-12">
         <%= f.submit 'SAVE', class: "btn btn-primary col-md-3"%>
            </div>
          </div>
    </div>
   </div>
      <% end %>
   </div>
   <div class="clearfix"></div>
      <div class="x_content">
    </div>
  </div> 
</div>
           ... </div>...
            <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
              <p>xxFood truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo
            booth letterpress, commodo enim craft beer mlkshk </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$('#category_id').change(function() {
    var value =  $('#category_id').val();
     $.ajax({
        url:'get_brand',
        type:'POST',
        dataType:'json',
        data:{
            valueCat: value,
        },
        dataType: 'script',
        success:function(data){
          console.log(data);
        },
        error:function(data){
            debugger;
        }
    });
  });
</script>